import Link from 'next/link';
import type { Metadata } from 'next';
import { Icon } from '@/components/ui/Icon';
import { Callout } from '@/components/widgets/Callout';
import { datasetModules, getDatasets } from '@/lib/content';

export const metadata: Metadata = {
  title: 'Dataset registry',
  description:
    'Five synthetic datasets with documented grain, units and planted defects — the answer key is deliberate.',
};

export default function DataIndex() {
  const datasets = getDatasets();
  const quirkCount = datasets.reduce((s, d) => s + d.quirks.length, 0);

  return (
    <div className="mx-auto max-w-wide px-4 py-10">
      <header>
        <h1 className="text-3xl font-bold text-ink">Dataset registry</h1>
        <p className="mt-2 max-w-content text-lg text-muted">
          Five datasets recur through the whole course, so you never waste time learning a new
          schema when you should be learning a new skill. Every one is documented: source, grain,
          units and known quirks — {quirkCount} planted defects in total.
        </p>
      </header>

      <div className="mt-6 max-w-content">
        <Callout type="info" title="Why they’re synthetic">
          <p>
            All five are generated by a script with a fixed random seed. Licensing (real market
            data can&apos;t be redistributed), teaching (we plant exactly the defects you need to
            find), and auditability (anyone can regenerate byte-identical data).
          </p>
        </Callout>
      </div>

      <ul className="mt-8 grid gap-4 lg:grid-cols-2">
        {datasets.map((ds) => {
          const modules = datasetModules(ds);

          return (
            <li key={ds.id}>
              <div className="card flex h-full flex-col p-5">
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <h2 className="text-lg font-semibold text-ink">
                      <Link href={`/data/${ds.id}`} className="no-underline hover:underline">
                        {ds.title}
                      </Link>
                    </h2>
                    <p className="mt-0.5 font-mono text-xs text-muted">{ds.id}</p>
                  </div>
                  <span className="chip shrink-0 bg-surface-alt font-mono text-muted">
                    {ds.rows.toLocaleString('en-IN')} × {ds.cols}
                  </span>
                </div>

                <dl className="mt-4 space-y-2 text-sm">
                  <div>
                    <dt className="text-xs font-semibold uppercase tracking-wide text-muted">
                      Grain
                    </dt>
                    <dd className="text-ink">{ds.grain}</dd>
                  </div>
                  <div>
                    <dt className="text-xs font-semibold uppercase tracking-wide text-muted">
                      Units
                    </dt>
                    <dd className="text-ink">{ds.units}</dd>
                  </div>
                </dl>

                <div className="mt-4">
                  <p className="text-xs font-semibold uppercase tracking-wide text-muted">
                    Planted defects
                  </p>
                  <ul className="mt-1.5 flex flex-wrap gap-1.5">
                    {ds.quirks.map((q) => (
                      <li key={q.code}>
                        <span
                          className="chip bg-warn/12 text-warn"
                          title={`${q.quirk} — teaches ${q.teaches}`}
                        >
                          {q.code}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>

                {modules.length > 0 && (
                  <p className="mt-4 flex flex-wrap gap-1.5 text-xs text-muted">
                    Used in{' '}
                    {modules.map((m) => (
                      <Link
                        key={m.id}
                        href={`/modules/${m.id}`}
                        className="font-medium text-ink no-underline hover:underline"
                      >
                        M{m.number}
                      </Link>
                    ))}
                  </p>
                )}

                <div className="mt-auto flex flex-wrap items-center gap-2 pt-5">
                  <Link href={`/data/${ds.id}`} className="btn-secondary no-underline">
                    <Icon name="eye" size={15} />
                    Inspect
                  </Link>
                  <a href={ds.rawUrl} download className="btn-ghost no-underline">
                    <Icon name="download" size={15} />
                    Download CSV
                  </a>
                </div>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
